name: Check PR

on: [push]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: rayepps/require-semver-bump@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-regex-pattern: >
            VERSION = [\\'\\"](.+?)[\\'\\"]
          version-file-path: 'version.py'
  publish-to-test-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt
      - name: Build a binary wheel and a source tarball
        run: make create-dist
      - uses: rayepps/require-push-to-pr@v1
        id: 'require_push'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish distribution 📦 to Test PyPI
        if: steps.require_push.outputs.pass == 'true'
        run: >
          make test-upload-dist token=${{ secrets.test_pypi_token }}
