name: Python package

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.test.txt
          make setup-swagger-cli
      - name: Lint
        run: make lint
      - name: Test with pytest
        run: make test

  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: rayepps/require-semver-bump@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  upload-to-test-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: rayepps/require-push-to-pr@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install pep517
        run: python -m pip install pep517 --user
      - name: Build a binary wheel and a source tarball
        run: python -m pep517.build --source --binary --out-dir dist/
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master # 37e305e7413032d8422456179fee28fac7d25187
        with:
          user: __token__
          password: ${{ secrets.test_pypi_token }}
          repository_url: https://test.pypi.org/legacy
